name: Docker Image CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/mozcomputing/better-call-reward:${{ github.ref_name }}
          docker build . --file Dockerfile --tag ghcr.io/mozcomputing/better-call-reward:latest
          docker push ghcr.io/mozcomputing/better-call-reward:${{ github.ref_name }}
          docker push ghcr.io/mozcomputing/better-call-reward:latest
          
